# Generated by Django 4.1.1 on 2022-09-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("votes", models.IntegerField(default=0)),
                ("menu_monday", models.TextField(blank=True)),
                ("menu_tuesday", models.TextField(blank=True)),
                ("menu_wednesday", models.TextField(blank=True)),
                ("menu_thursday", models.TextField(blank=True)),
                ("menu_friday", models.TextField(blank=True)),
                ("menu_saturday", models.TextField(blank=True)),
                ("menu_sunday", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote",
                        to="menu_choice.restaurant",
                    ),
                ),
            ],
        ),
    ]
